### ISSUE TITLE
Source maps in production build

### ISSUE THREAD

**Issue by mevinDhun** [antonybudianto/angular2-starter#151]
Is it possible to have external source maps in the production build? I enabled the source map option in the system builder config:
```javascript
var systemJs = {
        builder: {
            normalize: true,
            minify: true,
            mangle: true,
            runtime: false,
            sourceMaps: true,
            globalDefs: {
                DEBUG: false,
                ENV: 'production'
            }
        }
    }; 
```
I can see the maps being generated but they are not being copied the build folder. I copied the _bundle.js.map_ to the build folder manually, Chrome says source map available, but they are not displayed correctly. They instead show index.html code as shown in the screenshot below.

![screen shot 2016-09-11 at 7 28 40 pm](https://cloud.githubusercontent.com/assets/17478561/18418385/4065b728-7856-11e6-9ccd-2969e7d59144.png)

Is there something i am missing? By the way, i see _lib.js_ also being generated, what does it contain and how is it created?

**Comment by antonybudianto** [comment]
lib.js is for global js packages, you can see them in `index.html` and it's generated using `gulp-useref`

for sourcemap, you can take a look at https://github.com/antonybudianto/angular2-starter/blob/master/config/gulp/tasks/typescript.js#L91
I don't know if sourcemap will work after being bundled since the original source file is in JS format
